export const SNACKBARS_AUTOHIDE_DURATION = 10000;

export const LOGGED_CLIENT_TOKEN = 'LOGGED_CLIENT_TOKEN';
export const LOGGED_CLIENT_NAME = 'LOGGED_CLIENT_NAME';

export const HEADER_HEIGHT = 64;
export const SIDEBAR_WIDTH = 80;
export const MOBILE_NAV_HEIGHT = 56;
export const MOBILE_BREAKPOINT = 768;

export const INPUT_DEBOUNCE_TIMEOUT = 500;
