#!/usr/bin/env bash
set -euo pipefail

: "${BACKUP_CRON:=0 3 * * *}"
: "${BACKUP_DIR:=/backups}"
: "${LOCAL_RETENTION_DAYS:=7}"
: "${RUN_ON_START:=false}"

mkdir -p "$BACKUP_DIR"

# Persist runtime env so the cron job can read it (cron strips most env vars).
# /etc/profile.d is read by bash; backup.sh is bash, so this works.
env | grep -E '^(PG|BACKUP_|RCLONE_|TZ=)' > /etc/backup.env

CRONTAB_FILE=/etc/crontabs/root
mkdir -p "$(dirname "$CRONTAB_FILE")"
cat > "$CRONTAB_FILE" <<EOF
# Generated by postgres-backup entrypoint
$BACKUP_CRON /usr/local/bin/backup.sh >> /proc/1/fd/1 2>> /proc/1/fd/2
EOF

echo "postgres-backup: cron schedule = '$BACKUP_CRON' (TZ=$TZ)"
echo "postgres-backup: local retention = ${LOCAL_RETENTION_DAYS} days"
if [ -n "${RCLONE_REMOTE:-}" ]; then
  echo "postgres-backup: remote target  = $RCLONE_REMOTE"
else
  echo "postgres-backup: remote target  = (none — local only)"
fi

if [ "$RUN_ON_START" = "true" ]; then
  echo "postgres-backup: RUN_ON_START=true, running initial backup"
  /usr/local/bin/backup.sh || echo "postgres-backup: initial backup failed — cron will retry on schedule"
fi

# busybox crond, foreground, log level 8 (info+), log to stdout
exec busybox crond -f -L /dev/stdout
