using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using NpgsqlTypes;

namespace EpoznamkyApi.Models;

public class Note
{
    public string Id { get; set; } = Guid.NewGuid().ToString();
    public string Title { get; set; } = string.Empty;
    public string Content { get; set; } = string.Empty;
    public string? FolderId { get; set; }
    public bool IsPinned { get; set; }
    public bool IsDeleted { get; set; }
    public long? DeletedAt { get; set; }
    public int Order { get; set; }
    public long CreatedAt { get; set; } = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
    public long UpdatedAt { get; set; } = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
    public long? SyncedAt { get; set; }
    public string UserId { get; set; } = string.Empty;

    // Full-text search vector (auto-generated by PostgreSQL)
    public NpgsqlTsVector? SearchVector { get; set; }

    // Navigation - not mapped to DB, populated via queries
    [NotMapped]
    public List<string> Tags { get; set; } = [];
    [NotMapped]
    public List<SharedUser> SharedWith { get; set; } = [];
}

// Junction table for Note <-> Tag many-to-many
public class NoteTag
{
    public string NoteId { get; set; } = string.Empty;
    public string TagId { get; set; } = string.Empty;
}

// Table for note sharing
public class NoteShare
{
    public string NoteId { get; set; } = string.Empty;
    public string SharedWithUserId { get; set; } = string.Empty;
    public string SharedWithEmail { get; set; } = string.Empty;
    public string Permission { get; set; } = "view"; // "view" or "edit"
}

// DTO for API responses
public class SharedUser
{
    public string UserId { get; set; } = string.Empty;
    public string Email { get; set; } = string.Empty;
    public string Permission { get; set; } = "view";
}

// Request DTOs
public class CreateNoteRequest
{
    [Required]
    [StringLength(500, MinimumLength = 1)]
    public string Title { get; set; } = string.Empty;

    [StringLength(5_000_000)]
    public string Content { get; set; } = string.Empty;

    [StringLength(36)]
    public string? FolderId { get; set; }

    [MaxLength(50)]
    public List<string> Tags { get; set; } = [];

    public bool IsPinned { get; set; }
}

public class UpdateNoteRequest
{
    [StringLength(500, MinimumLength = 1)]
    public string? Title { get; set; }

    [StringLength(5_000_000)]
    public string? Content { get; set; }

    public string? FolderId { get; set; }

    [MaxLength(50)]
    public List<string>? Tags { get; set; }

    public bool? IsPinned { get; set; }

    [Range(0, int.MaxValue)]
    public int? Order { get; set; }
}

public class ShareNoteRequest
{
    [Required]
    [EmailAddress]
    [StringLength(320)]
    public string Email { get; set; } = string.Empty;

    [Required]
    [RegularExpression("^(view|edit)$")]
    public string Permission { get; set; } = "view";
}

public class ReorderNotesRequest
{
    [Required]
    [MinLength(1)]
    [MaxLength(1000)]
    public List<NoteOrderItem> Items { get; set; } = [];
}

public class NoteOrderItem
{
    [Required]
    [StringLength(36, MinimumLength = 1)]
    public string Id { get; set; } = string.Empty;

    [Range(0, int.MaxValue)]
    public int Order { get; set; }
}
