#!/bin/sh

# Generate env.js from environment variables
cat > /usr/share/nginx/html/env.js << EOF
// Runtime environment configuration (generated by Docker)
window.API_URL = '${API_URL:-http://localhost:5000}';
window.KEYCLOAK_URL = '${KEYCLOAK_URL:-http://localhost:8080}';
window.KEYCLOAK_REALM = '${KEYCLOAK_REALM:-epoznamky}';
window.KEYCLOAK_CLIENT_ID = '${KEYCLOAK_CLIENT_ID:-epoznamky-frontend}';
window.MOCK_MODE = ${MOCK_MODE:-false};
EOF

echo "Generated env.js with:"
echo "  API_URL: ${API_URL:-http://localhost:5000}"
echo "  KEYCLOAK_URL: ${KEYCLOAK_URL:-http://localhost:8080}"
echo "  KEYCLOAK_REALM: ${KEYCLOAK_REALM:-epoznamky}"
echo "  KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID:-epoznamky-frontend}"

# Execute the main command
exec "$@"
