#!/bin/sh
# Runs during the nginxinc/nginx-unprivileged startup pipeline
# (/docker-entrypoint.d/). Rewrites env.js from runtime environment so the
# same image serves dev, staging, and prod with different backends.
set -eu

# Using ${VAR-default} (not :-) so an explicit empty string is preserved,
# not silently replaced by the default. API_URL=""  means "same-origin,"
# which is a valid production setup behind a reverse proxy.
cat > /usr/share/nginx/html/env.js <<EOF
// Runtime environment configuration (generated by Docker)
window.API_URL = '${API_URL-}';
window.KEYCLOAK_URL = '${KEYCLOAK_URL:-http://localhost:8080}';
window.KEYCLOAK_REALM = '${KEYCLOAK_REALM:-notes}';
window.KEYCLOAK_CLIENT_ID = '${KEYCLOAK_CLIENT_ID:-notes-frontend}';
EOF

echo "[40-write-env-js] Generated env.js:"
echo "  API_URL           = ${API_URL-}"
echo "  KEYCLOAK_URL      = ${KEYCLOAK_URL:-http://localhost:8080}"
echo "  KEYCLOAK_REALM    = ${KEYCLOAK_REALM:-notes}"
echo "  KEYCLOAK_CLIENT_ID = ${KEYCLOAK_CLIENT_ID:-notes-frontend}"
